// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/sand/store (interfaces: Watcher)

// Package storemock is a generated GoMock package.
package storemock

import (
	reflect "reflect"

	clientv3 "github.com/coreos/etcd/clientv3"
	gomock "github.com/golang/mock/gomock"
)

// MockWatcher is a mock of Watcher interface
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockWatcher) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockWatcherMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWatcher)(nil).Close))
}

// IsReady mocks base method
func (m *MockWatcher) IsReady() bool {
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady
func (mr *MockWatcherMockRecorder) IsReady() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockWatcher)(nil).IsReady))
}

// NextResponse mocks base method
func (m *MockWatcher) NextResponse() (clientv3.WatchResponse, bool) {
	ret := m.ctrl.Call(m, "NextResponse")
	ret0, _ := ret[0].(clientv3.WatchResponse)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// NextResponse indicates an expected call of NextResponse
func (mr *MockWatcherMockRecorder) NextResponse() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextResponse", reflect.TypeOf((*MockWatcher)(nil).NextResponse))
}

// Ready mocks base method
func (m *MockWatcher) Ready() {
	m.ctrl.Call(m, "Ready")
}

// Ready indicates an expected call of Ready
func (mr *MockWatcherMockRecorder) Ready() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockWatcher)(nil).Ready))
}

// WaitReady mocks base method
func (m *MockWatcher) WaitReady() {
	m.ctrl.Call(m, "WaitReady")
}

// WaitReady indicates an expected call of WaitReady
func (mr *MockWatcherMockRecorder) WaitReady() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitReady", reflect.TypeOf((*MockWatcher)(nil).WaitReady))
}
