// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/sand/network/overlay (interfaces: NetworkEndpointListener)

// Package overlaymock is a generated GoMock package.
package overlaymock

import (
	context "context"
	reflect "reflect"

	types "github.com/Scalingo/sand/api/types"
	netmanager "github.com/Scalingo/sand/network/netmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkEndpointListener is a mock of NetworkEndpointListener interface.
type MockNetworkEndpointListener struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkEndpointListenerMockRecorder
	isgomock struct{}
}

// MockNetworkEndpointListenerMockRecorder is the mock recorder for MockNetworkEndpointListener.
type MockNetworkEndpointListenerMockRecorder struct {
	mock *MockNetworkEndpointListener
}

// NewMockNetworkEndpointListener creates a new mock instance.
func NewMockNetworkEndpointListener(ctrl *gomock.Controller) *MockNetworkEndpointListener {
	mock := &MockNetworkEndpointListener{ctrl: ctrl}
	mock.recorder = &MockNetworkEndpointListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkEndpointListener) EXPECT() *MockNetworkEndpointListenerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockNetworkEndpointListener) Add(ctx context.Context, manager netmanager.NetManager, network types.Network) (chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, manager, network)
	ret0, _ := ret[0].(chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockNetworkEndpointListenerMockRecorder) Add(ctx, manager, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockNetworkEndpointListener)(nil).Add), ctx, manager, network)
}

// Remove mocks base method.
func (m *MockNetworkEndpointListener) Remove(ctx context.Context, network types.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockNetworkEndpointListenerMockRecorder) Remove(ctx, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockNetworkEndpointListener)(nil).Remove), ctx, network)
}
