version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    reviewers:
      - "Soulou"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Soulou"
