version: 2

before:
  hooks:
    - go mod tidy
builds:
  - id: sand-agent
    binary: sand-agent
    main: ./cmd/sand-agent
    env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
    goos:
      - linux
    ldflags:
      - -X config.Version={{.Version}}
  - id: sand-agent-cli
    binary: sand-agent-cli
    main: ./cmd/sand-agent-cli
    env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
    goos:
      - linux
    ldflags:
      - -X main.Version={{.Version}}
archives:
  - formats: [ tar.gz ]
    ids:
      - sand-agent
      - sand-agent-cli
    version_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
checksum:
  version_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
