services:
  web:
    build: .
    pid: "host"
    network_mode: "host"
    privileged: true
    volumes:
      - ./:/go/src/github.com/Scalingo/sand
      - /var/run/netns:/var/run/netns:shared
      - /var/run/docker/netns:/var/run/docker/netns:shared
      - /etc/docker/plugins:/etc/docker/plugins:shared
    environment:
      GO_ENV: development
      ETCD_HOSTS: "https://192.168.56.2:22379,https://192.168.56.2:22381,https://192.168.56.2:22383"
      PEER_IP: "192.168.56.2"
      ENABLE_DOCKER_PLUGIN: "true"
    ports:
      - 9999:9999
      - 9998:9998
    command: reflex -r '\.go$$' -s -- sh -c 'go install -buildvcs=false github.com/Scalingo/sand/cmd/sand-agent && /go/bin/sand-agent'
  etcd-1:
    volumes:
      - /var/etcd-vm-1:/data/etcd
    image: quay.io/coreos/etcd:v3.5.17
    command: "etcd --name etcd-1 --data-dir /data/etcd \
      --listen-client-urls https://0.0.0.0:2379 \
      --listen-peer-urls https://0.0.0.0:2380 \
      --advertise-client-urls https://192.168.56.2:22379 \
      --initial-advertise-peer-urls https://192.168.56.2:22380 \
      --auto-tls \
      --peer-auto-tls \
      --initial-cluster-state new \
      --initial-cluster-token token-cluster \
      --initial-cluster 'etcd-1=https://192.168.56.2:22380,etcd-2=https://192.168.56.2:22382,etcd-3=https://192.168.56.2:22384' \
      "
    ports:
      - 22379:2379
      - 22380:2380
  etcd-2:
    volumes:
      - /var/etcd-vm-2:/data/etcd
    image: quay.io/coreos/etcd:v3.5.17
    command: "etcd --name etcd-2 --data-dir /data/etcd \
      --listen-client-urls https://0.0.0.0:2379 \
      --listen-peer-urls https://0.0.0.0:2380 \
      --advertise-client-urls https://192.168.56.2:22381 \
      --initial-advertise-peer-urls https://192.168.56.2:22382 \
      --auto-tls \
      --peer-auto-tls \
      --initial-cluster-state new \
      --initial-cluster-token token-cluster \
      --initial-cluster 'etcd-1=https://192.168.56.2:22380,etcd-2=https://192.168.56.2:22382,etcd-3=https://192.168.56.2:22384' \
      "
    ports:
      - 22381:2379
      - 22382:2380
  etcd-3:
    volumes:
      - /var/etcd-vm-3:/data/etcd
    image: quay.io/coreos/etcd:v3.5.17
    command: "etcd --name etcd-3 --data-dir /data/etcd \
      --listen-client-urls https://0.0.0.0:2379 \
      --listen-peer-urls https://0.0.0.0:2380 \
      --advertise-client-urls https://192.168.56.2:22383 \
      --initial-advertise-peer-urls https://192.168.56.2:22384 \
      --auto-tls \
      --peer-auto-tls
      --initial-cluster-state new \
      --initial-cluster-token token-cluster \
      --initial-cluster 'etcd-1=https://192.168.56.2:22380,etcd-2=https://192.168.56.2:22382,etcd-3=https://192.168.56.2:22384' \
      "
    ports:
      - 22383:2379
      - 22384:2380
  etcdctl3:
    image: quay.io/coreos/etcd:v3.3.17
    stop_signal: SIGKILL
    command: "tail -F /dev/null"
    environment:
      ETCDCTL_API: 3
      ETCDCTL_ENDPOINTS: http://192.168.56.2:22379,http://192.168.56.2:22381,http://192.168.56.2:22383
