dependencies = []
description = "SAND is a overlay network manager. It aims at creating private networks for database cluster on demand"
destination_server = ["database-hosting-node"]
flags = ["cli"]
languages = ["go"]
owner = "leo@scalingo.com"
team = "IST"
version = "1.1.0"
