// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/sand/store (interfaces: Registration)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/leo/go/src/github.com/Scalingo/sand/store/storemock/registration_mock.go -package storemock github.com/Scalingo/sand/store Registration
//

// Package storemock is a generated GoMock package.
package storemock

import (
	reflect "reflect"

	v3 "go.etcd.io/etcd/client/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistration is a mock of Registration interface.
type MockRegistration struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationMockRecorder
	isgomock struct{}
}

// MockRegistrationMockRecorder is the mock recorder for MockRegistration.
type MockRegistrationMockRecorder struct {
	mock *MockRegistration
}

// NewMockRegistration creates a new mock instance.
func NewMockRegistration(ctrl *gomock.Controller) *MockRegistration {
	mock := &MockRegistration{ctrl: ctrl}
	mock.recorder = &MockRegistrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistration) EXPECT() *MockRegistrationMockRecorder {
	return m.recorder
}

// EventChan mocks base method.
func (m *MockRegistration) EventChan() <-chan *v3.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventChan")
	ret0, _ := ret[0].(<-chan *v3.Event)
	return ret0
}

// EventChan indicates an expected call of EventChan.
func (mr *MockRegistrationMockRecorder) EventChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventChan", reflect.TypeOf((*MockRegistration)(nil).EventChan))
}

// Unregister mocks base method.
func (m *MockRegistration) Unregister() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister")
}

// Unregister indicates an expected call of Unregister.
func (mr *MockRegistrationMockRecorder) Unregister() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockRegistration)(nil).Unregister))
}
