// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/sand/network/netmanager (interfaces: NetManager)

// Package netmanagermock is a generated GoMock package.
package netmanagermock

import (
	context "context"
	reflect "reflect"

	types "github.com/Scalingo/sand/api/types"
	gomock "github.com/golang/mock/gomock"
)

// MockNetManager is a mock of NetManager interface
type MockNetManager struct {
	ctrl     *gomock.Controller
	recorder *MockNetManagerMockRecorder
}

// MockNetManagerMockRecorder is the mock recorder for MockNetManager
type MockNetManagerMockRecorder struct {
	mock *MockNetManager
}

// NewMockNetManager creates a new mock instance
func NewMockNetManager(ctrl *gomock.Controller) *MockNetManager {
	mock := &MockNetManager{ctrl: ctrl}
	mock.recorder = &MockNetManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNetManager) EXPECT() *MockNetManagerMockRecorder {
	return m.recorder
}

// AddEndpointNeigh mocks base method
func (m *MockNetManager) AddEndpointNeigh(arg0 context.Context, arg1 types.Network, arg2 types.Endpoint) error {
	ret := m.ctrl.Call(m, "AddEndpointNeigh", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEndpointNeigh indicates an expected call of AddEndpointNeigh
func (mr *MockNetManagerMockRecorder) AddEndpointNeigh(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEndpointNeigh", reflect.TypeOf((*MockNetManager)(nil).AddEndpointNeigh), arg0, arg1, arg2)
}

// Ensure mocks base method
func (m *MockNetManager) Ensure(arg0 context.Context, arg1 types.Network) error {
	ret := m.ctrl.Call(m, "Ensure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure
func (mr *MockNetManagerMockRecorder) Ensure(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockNetManager)(nil).Ensure), arg0, arg1)
}

// EnsureEndpointsNeigh mocks base method
func (m *MockNetManager) EnsureEndpointsNeigh(arg0 context.Context, arg1 types.Network, arg2 []types.Endpoint) error {
	ret := m.ctrl.Call(m, "EnsureEndpointsNeigh", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureEndpointsNeigh indicates an expected call of EnsureEndpointsNeigh
func (mr *MockNetManagerMockRecorder) EnsureEndpointsNeigh(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureEndpointsNeigh", reflect.TypeOf((*MockNetManager)(nil).EnsureEndpointsNeigh), arg0, arg1, arg2)
}
