// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Scalingo/sand/ipallocator (interfaces: IPAllocator)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination /home/leo/go/src/github.com/Scalingo/sand/test/mocks/ipallocatormock/ipallocator_mock.go -package ipallocatormock github.com/Scalingo/sand/ipallocator IPAllocator
//

// Package ipallocatormock is a generated GoMock package.
package ipallocatormock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	ipallocator "github.com/Scalingo/sand/ipallocator"
)

// MockIPAllocator is a mock of IPAllocator interface.
type MockIPAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockIPAllocatorMockRecorder
	isgomock struct{}
}

// MockIPAllocatorMockRecorder is the mock recorder for MockIPAllocator.
type MockIPAllocatorMockRecorder struct {
	mock *MockIPAllocator
}

// NewMockIPAllocator creates a new mock instance.
func NewMockIPAllocator(ctrl *gomock.Controller) *MockIPAllocator {
	mock := &MockIPAllocator{ctrl: ctrl}
	mock.recorder = &MockIPAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPAllocator) EXPECT() *MockIPAllocatorMockRecorder {
	return m.recorder
}

// AllocateIP mocks base method.
func (m *MockIPAllocator) AllocateIP(ctx context.Context, id string, opts ipallocator.AllocateIPOpts) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllocateIP", ctx, id, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllocateIP indicates an expected call of AllocateIP.
func (mr *MockIPAllocatorMockRecorder) AllocateIP(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllocateIP", reflect.TypeOf((*MockIPAllocator)(nil).AllocateIP), ctx, id, opts)
}

// ReleaseIP mocks base method.
func (m *MockIPAllocator) ReleaseIP(ctx context.Context, id, address string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseIP", ctx, id, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseIP indicates an expected call of ReleaseIP.
func (mr *MockIPAllocatorMockRecorder) ReleaseIP(ctx, id, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseIP", reflect.TypeOf((*MockIPAllocator)(nil).ReleaseIP), ctx, id, address)
}

// ReleasePool mocks base method.
func (m *MockIPAllocator) ReleasePool(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePool", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleasePool indicates an expected call of ReleasePool.
func (mr *MockIPAllocatorMockRecorder) ReleasePool(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePool", reflect.TypeOf((*MockIPAllocator)(nil).ReleasePool), ctx, id)
}
